\c  dev_products;




INSERT INTO products (name, price, description, image, type) VALUES
('Barra de Pan', 100, 'Nuestra barra básica y habitual. De masa madre y harina de trigo ecológica.
La elaboran todos los días nuestros maestros panaderos en nuestros obradores, con especial atención a los tiempos de fermentado para aportarle un inconfundible sabor artesanal.
Como en todos nuestros panes solo usamos los mejores ingredientes naturales, masas madres propias, largas fermentaciones, reposos sobre las telas de nilo y todo ello cocido en horno refractario de solera.','https://freepikpsd.com/file/2019/10/barra-pan-png-7-Transparent-Images.png','Savory'),
('Baguette', 140, 'La clásica Baguette, en francés literalmente "varita".
Es una variedad de pan caracterizada por ser mucho mas larga que ancha y, además, por su corteza crujiente.
En Bonifacio es una de nuestras especialidades, muy demandada por su sabor característico y su inigualable sabor.','https://www.pngkey.com/png/full/916-9167788_baguette.png', 'Savory'),
('Barra de Pan Candeal', 140, 'Tiene muchos nombres, pan de picos, candeal, castellana o colón.
El pan candeal es un tipo de pan tradicional de algunas zonas de España que se elabora habitualmente con trigo candeal.
Se caracteriza por su miga densa y prieta, su poca hidratacion y una corteza fina, de superficie lisa y color dorado.', 'https://panamarbakery.com/public/Image/2021/3/161546665912912normal_Galeria.png', 'Savory'), ('Croissants Rellenos', 170, 'Horneados a diario nuestros croissants los puedes elegir de: Pavo y queso, Salmón con huevo duro y queso, Cangrejo con salsa rosa, Vegetal con atún y huevo,
Atún, cebolla y mahonesa','https://toast-local-nyc3-production.nyc3.cdn.digitaloceanspaces.com/restaurants/3986b31d-c177-49f9-8a29-2e6d3cba5204/croissant-hamcheese-menuitem-346955-1198.webp','Savory'), ('Napolitana de chocolate', 170, 'Napolitana de hojaldre con relleno de crema de chocolate y virutas de chocolate por encima', 'https://medbar.es/wp-content/uploads/2018/08/Napolitana-chocolate.png', 'Sweet'), ('Caracola',2.00,'Nuestra caracola esta hecha con crema pastelera untuosa, gramaje generoso, numerosas pasas azucaradas de forma natural y un hojaldrado ligero y crujiente. Todas las mañanas es horneada por nuestros maestros panaderos.','https://imgur.com/4j5TLnc', 'Sweet'), ('Napolitana de crema', 1.70,'Riquísima napolitana de hojaldre rellena con crema pastelera. Horneada cada mañana por nuestros panaderos.' ,'https://angellinares.es/137334-large_default/napolitana-magno-crema-140g.jpg', 'Sweet'), ('Palmeritas de Chocolate', 1.75 ,'Todos los días nuestros maestros panaderos elaboran estas riquísimas palmeritas de hojaldre y las bañan en rico chocolate fundido, después las enfrían y dan toque a estas delicias de chocolate.', 'https://imgur.com/a5x08Gg', 'Sweet'), ('Tarta Mousse Chocolate',24.00, 'Fina base de bizcocho con una ganache de chocolate recubierto de una exquisita mousse de chocolate puro.', 'https://imgur.com/a/hEh70G6', 'Cake'),
('Tarta de Fresas', 2400, 'Finas capas de bizcocho acompañadas de una capa de crema pastelera,  nata montada natural y mermelada de fresa, todo ello decorado con nata y fresas naturales.','https://imgur.com/s8OlFea' ,'Cake'), ('Tarta de Sara', 2400, 'Cuenta que Sarah Bernhadrt era una actriz francesa de teatro y cine, incluso se consideraba la más importante del siglo XIX y la mas famosa de la historia. Tanto fue la fama que alcanzó que inspiró la creación de este delicioso postre que ahora lleva por nombre tarta Sara. Este pastel esta formado por un esponjoso bizcocho genovés, empapado en almíbar y esta relleno y cubierto por una crema de mantequilla. Además está decorado con almendra laminada y cerezas.', 'https://imgur.com/eqlbyZg', 'Cake'),('Tarta de Zanahoria', 2400,'Capas de bizcocho  elaborado a base de harina integral, azúcar moreno y zanahoria con un toque de canela, acompañadas de crema de queso rebajado con nata. Una explosión perfecta de sabores en tu boca.','https://imgur.com/dz5Qgvg','Cake'),('Tarta de Septembre', 7000, 'Capas de piononos o bizcochos de vainilla rellenos de crema de chocolate, y fresa espcial de Septembre','https://imgur.com/LYsrpeq', 'Cake')

